version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: user_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  mongodb_activity:
    image: mongodb/mongodb-community-server:latest
    container_name: ai_db
    restart: unless-stopped
    ports:
      - "27018:27018"
    volumes:
      - activity_db_data:/data/db
      - ./.mongo-init/init-activity-db.js:/docker-entrypoint-initdb.d/init.js

  mongodb_ai:
    image: mongodb/mongodb-community-server:latest
    container_name: activity_db
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ai_db_data:/data/db
      - ./.mongo-init/init-ai-db.js:/docker-entrypoint-initdb.d/init.js

volumes:
  pgdata:
  activity_db_data: {}
  ai_db_data: {}