spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: ronaldoadmin123

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking