spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: ronaldoadmin123
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}