spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect